// Package coveragedoc renders docs/COVERAGE.md from code (PRD #513, slice
// #514).
//
// COVERAGE.md used to be a hand-maintained table of ~43 *surface* rows standing
// in for 181 Discovery methods, and it drifted: rows claimed ✅ for methods the
// CLI never calls. The fix is to stop writing it. The universe of methods comes
// from the committed existence index (docs/discovery/paths.txt), what the CLI
// calls comes from internal/apiregistry, and what will never be wrapped comes
// from apiregistry.Exclusions. Everything else is uncovered, by subtraction, so
// no row can lie.
//
// Render is deterministic (same inputs, byte-identical output) so the freshness
// test in this package can re-render and compare bytes, exactly like the Schema
// index gate in internal/schemaindex.
package coveragedoc

import (
	"bufio"
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/PollyGlot/google-play-cli/internal/apiregistry"
	"github.com/PollyGlot/google-play-cli/internal/discovery"
)

// State is one of the three answers a method can get. There is no fourth: a
// method is called, excluded by nature, or a gap.
type State int

const (
	// Uncovered: in scope under ADR-0026, no command calls it yet.
	Uncovered State = iota
	// Called: at least one shipped command calls it (apiregistry.Entries).
	Called
	// Excluded: never to be wrapped (apiregistry.Exclusions).
	Excluded
)

// Render produces the full contents of docs/COVERAGE.md. paths is the raw
// docs/discovery/paths.txt (`id⇥verb⇥path` per line), the same artefact the
// registry tests anchor to.
func Render(paths []byte) ([]byte, error) {
	ids, err := methodIDs(paths)
	if err != nil {
		return nil, err
	}

	called := map[string]apiregistry.Entry{}
	for _, e := range apiregistry.Entries() {
		called[e.MethodID] = e
	}
	excluded := map[string]string{}
	for _, x := range apiregistry.Exclusions() {
		excluded[x.MethodID] = x.Reason
	}

	// An id in the registry or the exclusion list that paths.txt does not know
	// would silently vanish from the rendered file: refuse to render instead.
	// (The registry tests catch it too; failing here keeps the generator from
	// committing a quietly incomplete document.)
	known := map[string]bool{}
	for _, id := range ids {
		known[id] = true
	}
	for id := range called {
		if !known[id] {
			return nil, fmt.Errorf("registry method %q is absent from paths.txt: run `make discovery-update`, or fix the id", id)
		}
	}
	for id := range excluded {
		if !known[id] {
			return nil, fmt.Errorf("excluded method %q is absent from paths.txt: run `make discovery-update`, or fix the id", id)
		}
	}
	for id := range called {
		if _, dup := excluded[id]; dup {
			return nil, fmt.Errorf("method %q is both registered and excluded: a method the CLI calls is not excluded by nature", id)
		}
	}

	var b bytes.Buffer
	writeHeader(&b)
	writeHeadline(&b, ids, called, excluded)
	for _, svc := range discovery.Services {
		writeService(&b, svc, ids, called, excluded)
	}
	writeFooter(&b)
	return b.Bytes(), nil
}

// methodIDs parses paths.txt and returns its ids sorted. paths.txt is already
// sorted, but sorting here makes the rendering independent of the producer.
func methodIDs(paths []byte) ([]string, error) {
	var ids []string
	seen := map[string]bool{}
	sc := bufio.NewScanner(bytes.NewReader(paths))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		id, _, ok := strings.Cut(line, "\t")
		if !ok {
			return nil, fmt.Errorf("paths.txt line %q is not `id\\tverb\\tpath`", line)
		}
		if seen[id] {
			return nil, fmt.Errorf("paths.txt lists method %q twice", id)
		}
		seen[id] = true
		ids = append(ids, id)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("read paths.txt: %w", err)
	}
	if len(ids) == 0 {
		return nil, fmt.Errorf("paths.txt parsed empty: run `make discovery-update`")
	}
	sort.Strings(ids)
	return ids, nil
}

func writeHeader(b *bytes.Buffer) {
	b.WriteString(`# API Coverage Matrix

<!-- Generated by ` + "`make coverage-update`" + `. Do not edit by hand: an offline test
     compares this file against a re-render and fails on any hand-edit. -->

Every method of every API gplay snapshots, in one of three states. Generated
from ` + "`docs/discovery/paths.txt`" + ` (the method universe), ` + "`internal/apiregistry`" + `
(the methods shipped commands call) and its exclusion list, so a row cannot
claim coverage the code does not have.

Policy: under [ADR-0026](adr/0026-maximal-admin-api-coverage.md) **every Play
admin API is in scope**; only *runtime* APIs (purchase-token verification, Play
Integrity) are excluded by nature. Anything uncovered is a real gap, tracked in
GitHub Issues, not a judgement about whether it is worth shipping.

| Mark | State | Meaning |
|---|---|---|
| ✅ | called | at least one shipped ` + "`gplay`" + ` command calls it |
| ⚫️ | excluded | never to be wrapped, with the reason on the row |
| 🔴 | uncovered | in scope, no command calls it yet |

`)
}

func writeHeadline(b *bytes.Buffer, ids []string, called map[string]apiregistry.Entry, excluded map[string]string) {
	b.WriteString("## Headline\n\n")
	b.WriteString("| Service | Methods | ✅ called | ⚫️ excluded | 🔴 uncovered |\n")
	b.WriteString("|---|---:|---:|---:|---:|\n")

	var totMethods, totCalled, totExcluded, totUncovered int
	for _, svc := range discovery.Services {
		var n, c, x int
		for _, id := range ids {
			if serviceOf(id) != svc.Name {
				continue
			}
			n++
			switch state(id, called, excluded) {
			case Called:
				c++
			case Excluded:
				x++
			case Uncovered:
			}
		}
		fmt.Fprintf(b, "| `%s` %s | %d | %d | %d | %d |\n", svc.Name, svc.Version, n, c, x, n-c-x)
		totMethods, totCalled, totExcluded, totUncovered = totMethods+n, totCalled+c, totExcluded+x, totUncovered+(n-c-x)
	}
	fmt.Fprintf(b, "| **Total** | **%d** | **%d** | **%d** | **%d** |\n\n", totMethods, totCalled, totExcluded, totUncovered)

	if totMethods > 0 {
		fmt.Fprintf(b, "Of the %d admin methods (%d total minus the %d excluded by nature), "+
			"**%d are called** and **%d are uncovered**.\n\n",
			totMethods-totExcluded, totMethods, totExcluded, totCalled, totUncovered)
	}
}

func writeService(b *bytes.Buffer, svc discovery.Service, ids []string, called map[string]apiregistry.Entry, excluded map[string]string) {
	var rows []string
	for _, id := range ids {
		if serviceOf(id) != svc.Name {
			continue
		}
		rows = append(rows, id)
	}
	if len(rows) == 0 {
		return
	}

	fmt.Fprintf(b, "## `%s` %s (%d methods)\n\n", svc.Name, svc.Version, len(rows))
	b.WriteString("| Method | State | Commands / reason |\n|---|---|---|\n")
	for _, id := range rows {
		switch state(id, called, excluded) {
		case Called:
			fmt.Fprintf(b, "| `%s` | ✅ | %s |\n", id, calledDetail(called[id]))
		case Excluded:
			fmt.Fprintf(b, "| `%s` | ⚫️ | %s |\n", id, escapeCell(excluded[id]))
		case Uncovered:
			fmt.Fprintf(b, "| `%s` | 🔴 | |\n", id)
		}
	}
	b.WriteString("\n")
}

// calledDetail renders the commands (and the entry's "why" note, when it has
// one) as one cell.
func calledDetail(e apiregistry.Entry) string {
	cmds := make([]string, 0, len(e.Commands))
	for _, c := range e.Commands {
		cmds = append(cmds, "`gplay "+c+"`")
	}
	detail := strings.Join(cmds, ", ")
	if e.Note != "" {
		// A semicolon, not parentheses: several notes already carry their own
		// parenthesised ADR reference, and nesting them reads badly.
		detail += "; " + escapeCell(e.Note)
	}
	return detail
}

func writeFooter(b *bytes.Buffer) {
	b.WriteString(`## Maintenance

This file is output, not input. To change a row, change its source and
regenerate:

- a command starts (or stops) calling a method: edit ` + "`internal/apiregistry/registry.go`" + `;
- a method is runtime and will never be wrapped: edit ` + "`internal/apiregistry/exclusions.go`" + `,
  with a one-line reason;
- Google added or removed methods: ` + "`make discovery-update`" + `, then
  ` + "`make schema-index-update`" + `.

Then run ` + "`make coverage-update`" + ` and commit the result. A stale or hand-edited
file fails ` + "`go test ./internal/coveragedoc/`" + ` offline.
`)
}

// serviceOf returns the leading segment of a method id, which Discovery uses as
// the service discriminator.
func serviceOf(id string) string {
	svc, _, _ := strings.Cut(id, ".")
	return svc
}

func state(id string, called map[string]apiregistry.Entry, excluded map[string]string) State {
	if _, ok := called[id]; ok {
		return Called
	}
	if _, ok := excluded[id]; ok {
		return Excluded
	}
	return Uncovered
}

// escapeCell keeps free prose from breaking the Markdown table: a pipe would
// open a new column, a newline would end the row.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}
